// 0.3.127 (D) / 0.3.128 (A) / 0.3.130 (F) / 0.3.131 (A–D) — Ghostwire's own hit FX: two beats for a
// gun, a spell, a melee swing and a grenade.
//
// **The point of this file is that it depends on nothing.** Automated Animations, Sequencer, JB2A,
// socketlib and ds-aa-bridge are all installed on Michael's box and every one of them is optional
// here. Ghostwire ships its own sounds (assets/sfx/) and its own textures (assets/fx/, generated by
// tools/make-fx-assets.mjs), so a table with none of those modules still sees and hears a hit. A
// table with Sequencer and JB2A gets the prettier version of the same moments, and nothing else
// changes.
//
// Three decisions worth writing down:
//
//  1. **Sound is never optional; video always is.** The sounds are module assets, so they cannot
//     fail to resolve. The Sequencer path is tried first and, if Sequencer is absent or the file
//     will not resolve, the built-in beats run instead — not a no-op. "Graceful degradation"
//     that degrades to nothing is just a dependency with extra steps.
//  2. **This is beside B40, not on top of it.** scripts/sfx.mjs fires on `abilityUse` — the moment
//     you *use* the thing. This fires on `abilityResult` — the moment it *lands*. A burst from a
//     Streetsweeper is therefore two sounds: the muzzle (B40) and the impact (here). Neither file
//     knows about the other, and turning either off leaves the other working.
//  3. **The classifier still says no a lot, and it says it on purpose.** A bow, a Matrix Verb, a
//     Commander's shout and a Take Cover maneuver are all `null` and get nothing.
//
// ---------------------------------------------------------------------------------------------
// 0.3.131 — why the canvas was blank, and what changed
//
// Michael smoke-passed 0.3.130 with one hole in it: **Double Tap made a noise and rolled and drew
// nothing**, with Automated Animations switched off. Three separate faults, all of which had to go:
//
//  * **A1 — there was never a point to draw at.** `targetPoints` read `message.system.targetTokens`
//    and then the roller's live targets. Draw Steel 1.1.2 puts `targets` / `targetTokens` on
//    `BaseMessageModel`, which is the base for the message subtypes *without* parts; an ability use
//    is a `StandardModel`, whose schema is **`parts` and nothing else**. So `targetTokens` is
//    `undefined` on every ability card in the game, the fallback was the only source there ever
//    was, and any moment the roller's target set was empty — a Director rolling from a sheet, a
//    target released by a template, a re-roll off an old card — produced `via: "none"`: sound, no
//    picture. Targets now resolve through five sources in turn, and when there is genuinely nothing
//    downrange the shooter still gets a **muzzle flash at their own token** rather than nothing.
//  * **A2 — the picture was too small to see even when it ran.** Two- and three-pixel vector
//    strokes for 570 ms, at map zoom, over a lit token. The built-in beat is now **additive sprites
//    off `assets/fx/`** — a stretched tracer, a muzzle flare, an expanding ring, radial sparks —
//    sized in grid squares rather than pixels and held for 780 ms. The vectors survive as the floor
//    for the half-second before the textures finish loading.
//  * **A3 — only the person who rolled ever drew.** `createChatMessage` early-returns unless
//    `userId === game.user.id`, while `AudioHelper.play(…, true)` broadcasts the sound to the whole
//    table. Everyone heard the shot; one person saw it. The resolved points are now relayed over
//    the same native `game.socket` channel scripts/mark.mjs and scripts/chrome-damage.mjs already
//    use, so every client on that scene draws the same beat. Receivers draw the **built-in** path
//    only and stay silent: the sound is already broadcast, and Sequencer broadcasts its own video.
//
// A fourth thing the brief asked about turned out **not** to be the fault: Foundry 14.367 bundles
// PIXI **7.4.3** (`resources/app/node_modules/pixi.js`, and core itself calls `beginFill` and
// `lineStyle` in over a hundred places), so the v7 Graphics calls 0.3.127 shipped do run today.
// They would break the day Foundry moves to PIXI 8, so every vector call now goes through the
// shims in scripts/fx-canvas.mjs, which pick the v7 or the v8 form off the instance.
//
// 0.3.130 (F)'s teardown hardening is kept and widened: the live-effect Set now holds containers of
// sprites rather than a bare Graphics, and teardown destroys them children-first.
//
// Everything above the "Foundry registration" divider is Foundry-free so the 0.3.127, 0.3.128 and
// 0.3.131 wave smokes can run it under Node.

import { ammoCostForDsid } from "./ammo.mjs";
import { VEIL_SUMMON_DSIDS } from "./veil-summons.mjs";
import {
  addFxSprite, destroyDisplay, fillCircle, fxTexturesReady, layAlong, placeAt,
  preloadFxTextures, strokeArc, strokeCircle, strokePath, strokeQuad,
} from "./fx-canvas.mjs";

import { elementFx, elementForFx, elementOfAbility } from "./elements.mjs";

const MODULE_ID = "draw-steel-ghostwire";
const L = "GHOSTWIRE.HitFx";
const SFX = `modules/${MODULE_ID}/assets/sfx`;
const SOCKET = `module.${MODULE_ID}`;

/** The moments this file covers. 0.3.128 adds `spell`. */
export const HIT_FX_KINDS = Object.freeze(["gun", "spell", "melee", "grenade"]);

/**
 * Ability keywords that mean "this is a working, not a weapon".
 *
 * Draw Steel's own two supernatural keywords. `tech` is deliberately **not** here: a Wrench's drone
 * deploy and a Technomancer's construct both carry it, and a tool bag is not a bolt of anything. A
 * Technomancer's damaging workings carry `magic` alongside it and are caught by that.
 *
 * 0.3.132 (A1) adds `tech` back on a *much* narrower condition — see {@link TECH_BOLT_KEYWORD}.
 */
export const SPELL_KEYWORDS = Object.freeze(["magic", "psionic"]);

/**
 * 0.3.132 (A1) — chrome that throws something.
 *
 * A Cyborg's Kinetic Driver reads `tech` / `ranged` / `strike` and nothing else, so 0.3.131 filed it
 * under "not this file's business" and a graviton slug crossed the table in silence. `tech` on its
 * own still means nothing: the rule is `tech` **plus a ranged strike**, which leaves the drone
 * deploy and the tool bag out by construction. Kinetic flavour lands on the `lightning` row of
 * {@link SPELL_FLAVOURS} by name, which is the teal bolt Michael asked for.
 */
export const TECH_BOLT_KEYWORD = "tech";

/**
 * Abilities that must never draw a beat, whatever their keywords say.
 *
 * Every one of these *is* magic and several of them even roll damage, so no keyword rule reaches
 * them: they are the summons. {@link VEIL_SUMMON_DSIDS} is imported rather than copied so the list
 * cannot drift from the engine that places the tokens (scripts/veil-summons.mjs). A Zephyr
 * Companion with a target still under the crosshair threw a beam at that target while it was busy
 * putting a token on the canvas; the companion's own strike is the companion's, not the summoner's.
 *
 * The rest are constructs and sustained utilities whose cards are genuinely not an attack landing.
 * `elemental-shaping` is here because only one of its three modes is a hit, and that mode calls
 * {@link playHitFx} for itself from scripts/elementalist.mjs rather than being classified into one.
 */
export const NO_HIT_FX_DSIDS = Object.freeze([
  ...VEIL_SUMMON_DSIDS,
  "sentinel-spirit",
  "compile-sprite", "recompile", "sprite-redirect",
  "compile-agent", "decompile-agent",
  "gw-decompile-sprite", "gw-dismiss-elemental", "gw-dismiss-spirit",
  "read-the-weave", "elemental-shaping",
]);

/**
 * What each kind looks and sounds like.
 *
 * `sound` is a module asset and always plays. `sequencerFiles` are JB2A paths tried in order when
 * Sequencer is present; every one of them may be absent, and the built-in `travel` + `style` run
 * instead. `travel` is the origin→target beat and is skipped when there is no origin to throw from
 * (a grenade has none — it goes off where it lands).
 *
 * 0.3.131 adds the four numbers that make the built-in beat legible. They are all **multiples of
 * the scene's grid size**, never pixels, so the same profile reads the same on a 70 px city map and
 * a 200 px boarding action:
 *
 *  * `core`       — the hot inner tint. The beam and the flash use it; `color` stays the outer hue.
 *  * `beamWidth`  — thickness of the tracer / bolt.
 *  * `impactSize` — diameter the impact ring grows to.
 *  * `sparks`     — how many streaks the impact throws.
 */
export const HIT_FX_PROFILES = Object.freeze({
  gun: {
    sound: `${SFX}/arrow-hit.ogg`,
    sequencerFiles: ["jb2a.impact.005.orange", "jb2a.impact.001.blue"],
    travelFiles: ["jb2a.bullet.01.orange", "jb2a.ranged.03.projectile.01.orange"],
    travel: "tracer",
    travelMs: 220,
    style: "spark",
    color: 0xffcc66,
    core: 0xfff4d2,
    beamWidth: 0.16,
    impactSize: 1.8,
    sparks: 7,
  },
  spell: {
    sound: `${SFX}/spell-lightning.ogg`,
    sequencerFiles: ["jb2a.impact.005.blue", "jb2a.impact.001.blue"],
    travelFiles: ["jb2a.magic_missile.blue", "jb2a.energy_strands.range.standard.blue.01"],
    travel: "bolt",
    travelMs: 340,
    style: "burst",
    color: 0x8fd6ff,
    core: 0xeafaff,
    beamWidth: 0.30,
    impactSize: 2.2,
    sparks: 0,
  },
  melee: {
    sound: `${SFX}/punch.ogg`,
    sequencerFiles: ["jb2a.melee_generic.slash.01.orange", "jb2a.impact.005.orange"],
    travelFiles: ["jb2a.melee_attack.01.trail.01.white", "jb2a.melee_generic.slash.01.white"],
    travel: "lunge",
    travelMs: 200,
    style: "slash",
    color: 0xffffff,
    core: 0xffffff,
    beamWidth: 0.22,
    impactSize: 1.6,
    sparks: 4,
  },
  grenade: {
    // A3: 1.25 s, trimmed from the 8.8 s spell-fire-blast.ogg 0.3.127 shipped.
    sound: `${SFX}/grenade-boom.ogg`,
    sequencerFiles: ["jb2a.explosion.01.orange", "jb2a.explosion.02.blue"],
    travelFiles: [],
    travel: null,
    travelMs: 0,
    style: "burst",
    color: 0xff7733,
    core: 0xffe2b0,
    beamWidth: 0,
    impactSize: 3.4,
    sparks: 10,
  },
});

/**
 * Spell flavours, in match order. First hit wins, which is why `dark` sits above `lightning`: a Dark
 * Blast is corruption whatever else is in its name, and `fire` sits above both so Fire Blast is fire.
 * `arcane` has no pattern and is the fallback, so every spell has a sound even when its name says
 * nothing about its element (Hurl Element, Kinetic Driver's cousins, a Director's homebrew working).
 */
export const SPELL_FLAVOURS = Object.freeze([
  { key: "fire", match: /fire|flame|ember|pyro|\bburn|scorch|wildfire|incinerat/i, sound: `${SFX}/spell-fireball.ogg`, color: 0xff8a33, core: 0xffe0a8 },
  { key: "dark", match: /dark|drain|corrupt|curse|pact|penance|judg|void|rot|blight|wither/i, sound: `${SFX}/spell-dark-blast.ogg`, color: 0xb46bff, core: 0xecd8ff },
  { key: "lightning", match: /lightning|storm|thunder|shock|\barc\b|taser|kinetic|static/i, sound: `${SFX}/spell-lightning.ogg`, color: 0x9fd4ff, core: 0xf0fbff },
  { key: "arcane", match: null, sound: `${SFX}/spell-lightning.ogg`, color: 0x8fd6ff, core: 0xeafaff },
]);

/** A Ghostwire weapon SKU's `gear` stamp reduced to the facts the classifier needs. */
const RANGE_MELEE = "Adjacent";

/**
 * Which flavour a spell is, from its name. Never null — `arcane` is the floor.
 * @param {string} name
 * @returns {{key: string, sound: string, color: number, core: number}}
 */
export function spellFlavour(name = "") {
  const text = String(name ?? "");
  for (const flavour of SPELL_FLAVOURS) {
    if (!flavour.match) return flavour;
    if (flavour.match.test(text)) return flavour;
  }
  return SPELL_FLAVOURS[SPELL_FLAVOURS.length - 1];
}

/**
 * The profile for one hit, flavour folded in.
 *
 * Returns a fresh object rather than the frozen profile so a caller can read `sound` and `color`
 * without having to know that only spells vary.
 *
 * @param {string} kind
 * @param {string} [name]  The ability's name, for the spell flavour.
 * @returns {object|null}
 */
export function hitFxProfile(kind, name = "", { element = null } = {}) {
  const profile = HIT_FX_PROFILES[kind];
  if (!profile) return null;
  // 0.3.134 (E): an element the caller actually knows beats any guess made from the card's name.
  // Hurl Element's name says nothing about fire; the damage type on the card does, and that is what
  // scripts/elementalist.mjs writes there before the roll. The override applies to every kind, not
  // just `spell`, because an elemental summon's strike is classified as a melee hit and still has
  // a colour: an Electrical Zephyr's swipe should not be white.
  const elemental = elementFx(element);
  if (elemental) return { ...profile, ...elemental, flavour: String(element).toLowerCase() };
  if (kind !== "spell") return { ...profile, flavour: null };
  const flavour = spellFlavour(name);
  return { ...profile, sound: flavour.sound, color: flavour.color, core: flavour.core, flavour: flavour.key };
}

/**
 * Which FX an attack is, or `null` for "not this file's business".
 *
 * The order is the whole rule and each step earns its place:
 *
 *  1. A suppressed `_dsid` — a summon, a construct, a sustained utility — is nothing, first, before
 *     any keyword gets a vote (0.3.132 A2).
 *  2. A thrown Blast is a grenade even though its band reads Short.
 *  3. A `self` working throws nothing at anybody, so it is nothing (0.3.132 A2).
 *  4. An Adjacent-band weapon is melee even though it may be chrome (a Cyber-Spur).
 *  5. A weapon that eats rounds is a gun.
 *  6. An ability on the 0.3.128 ammo allowlist is a gun even with no gear behind it — that is how
 *     Controlled Pair gets a tracer and a bow does not.
 *  7. **Only now**: an ability with no `strike` keyword and no damage power effect is nothing
 *     (0.3.132 A2). This is the gate Read the Weave, Blessed Light and every buff / heal / ward in
 *     the Street Priest and Technomancer lists fall through — they all carry `magic`, and 0.3.131
 *     gave every one of them a bolt at whoever happened to still be targeted.
 *  8. A `magic` / `psionic` attack is a spell.
 *  9. A `tech` ranged strike is a spell too — Kinetic Driver (0.3.132 A1).
 * 10. A melee `strike` with no gear stamp is still a swing.
 *
 * Steps 2, 4, 5 and 6 are exactly 0.3.127's behaviour, unchanged, so every gear path that worked
 * still works: a gun is classified before the damage gate is ever consulted, because a SKU's stamp
 * is better evidence about a trigger pull than an ability's power effects are.
 *
 * `damaging` is deliberately tri-state. `null` means *unknown* — a caller that cannot see the power
 * effects (an older smoke, a Director's macro) gets 0.3.131's keyword behaviour rather than silence.
 *
 * @param {object} opts
 * @param {boolean} opts.thrownBlast      The source item carries `gear.thrown` (scripts/grenades.mjs).
 * @param {string}  opts.range            The SKU's `gear.range` band: Adjacent / Short / Medium / ...
 * @param {string|null} opts.ammoFamily   The SKU's `gear.ammoFamily` (0.3.126 B) — set only on guns.
 * @param {boolean} opts.gunAbility       The ability is on `AMMO_ABILITY_COSTS` (0.3.128 B).
 * @param {Iterable<string>} opts.keywords  The ability's `system.keywords`.
 * @param {string} opts.distanceType      The ability's `system.distance.type`.
 * @param {string} [opts.dsid]            The ability's `system._dsid`, for the suppression list.
 * @param {boolean|null} [opts.damaging]  Has a `damage` power effect; `null` when unknown.
 * @returns {"gun"|"spell"|"melee"|"grenade"|null}
 */
export function classifyHit({
  thrownBlast = false, range = "", ammoFamily = null,
  gunAbility = false, keywords = [], distanceType = "",
  dsid = "", damaging = null,
} = {}) {
  if (NO_HIT_FX_DSIDS.includes(String(dsid ?? ""))) return null;
  if (thrownBlast) return "grenade";
  if (distanceType === "self") return null;
  if (range === RANGE_MELEE) return "melee";
  if (ammoFamily) return "gun";
  if (gunAbility) return "gun";
  const kw = new Set(keywords ?? []);
  const strike = kw.has("strike");
  if (!strike && (damaging === false)) return null;
  if (SPELL_KEYWORDS.some(keyword => kw.has(keyword))) return "spell";
  if (strike && kw.has(TECH_BOLT_KEYWORD) && (kw.has("ranged") || (distanceType === "ranged"))) return "spell";
  if (strike && ((distanceType === "melee") || (kw.has("melee") && !kw.has("ranged")))) return "melee";
  return null;
}

/**
 * Does this ability's power actually roll damage?
 *
 * Reads `system.power.effects` in both shapes the system hands it over in — a plain object on a pack
 * row, a Collection on a live Item — and returns `null` when there is nothing to read at all, which
 * {@link classifyHit} takes as "unknown" rather than as "no".
 *
 * @param {object} system  An ability's `system`.
 * @returns {boolean|null}
 */
export function hasDamageEffect(system) {
  const effects = system?.power?.effects;
  if (!effects) return null;
  const list = Array.isArray(effects)
    ? effects
    : ((typeof effects.values === "function") ? [...effects.values()] : Object.values(effects));
  return list.some(effect => (effect?.type ?? effect?.constructor?.TYPE) === "damage");
}

/* ============================================ Foundry registration */

const gearFlags = item => item?.flags?.[MODULE_ID]?.gear ?? item?.getFlag?.(MODULE_ID, "gear") ?? null;

/**
 * The caster's Elementalist attunement, as the 0.3.135 (2) colour fallback.
 *
 * Read by flag name rather than imported from scripts/elementalist.mjs, because **that file already
 * imports this one** (`playHitFx`) and an import cycle here would resolve to `undefined` at load
 * depending on which module Foundry reaches first. `tools/wave-03135-smoke.mjs` asserts this literal
 * against `ATTUNEMENT_FLAG`, so the two cannot drift apart silently.
 */
const attunementOf = actor =>
  String(actor?.getFlag?.(MODULE_ID, "attunement") ?? actor?.flags?.[MODULE_ID]?.attunement ?? "");

const trace = (...args) => {
  if (CONFIG?.debug?.ghostwireHitFx) console.debug(`${MODULE_ID} | hit FX |`, ...args);
};

/* -------------------------------------------- settings */

function registerSettings() {
  game.settings.register(MODULE_ID, "hitFxEnabled", {
    name: `${L}.Settings.Enabled.Name`, hint: `${L}.Settings.Enabled.Hint`,
    scope: "world", config: true, type: Boolean, default: true,
  });
  game.settings.register(MODULE_ID, "hitFxVolume", {
    name: `${L}.Settings.Volume.Name`, hint: `${L}.Settings.Volume.Hint`,
    scope: "client", config: true, type: Number, default: 0.7,
    range: { min: 0, max: 1, step: 0.05 },
  });
  game.settings.register(MODULE_ID, "hitFxSequencer", {
    name: `${L}.Settings.Sequencer.Name`, hint: `${L}.Settings.Sequencer.Hint`,
    scope: "world", config: true, type: Boolean, default: true,
  });
  // 0.3.131 (A3). Off means the old behaviour: only the client that rolled sees the beat.
  game.settings.register(MODULE_ID, "hitFxBroadcast", {
    name: `${L}.Settings.Broadcast.Name`, hint: `${L}.Settings.Broadcast.Hint`,
    scope: "world", config: true, type: Boolean, default: true,
  });
}

const enabled = () => {
  try {
    return game.settings.get(MODULE_ID, "hitFxEnabled") !== false;
  } catch {
    return false;                                  // asked before `init` registered the setting
  }
};

const volume = () => {
  try {
    return Number(game.settings.get(MODULE_ID, "hitFxVolume") ?? 0.7);
  } catch {
    return 0.7;
  }
};

const broadcasting = () => {
  try {
    return game.settings.get(MODULE_ID, "hitFxBroadcast") !== false;
  } catch {
    return false;
  }
};

/* -------------------------------------------- the optional pretty path */

/** Sequencer, if the table has it turned on and this world has not opted out. */
function sequencer() {
  try {
    if (game.settings.get(MODULE_ID, "hitFxSequencer") === false) return null;
  } catch {
    return null;
  }
  if (!game.modules.get("sequencer")?.active) return null;
  return globalThis.Sequence ?? null;
}

/**
 * First JB2A path that actually resolves in Sequencer's database, or null.
 *
 * Every lookup is guarded: `Sequencer.Database` is another module's surface, and a Ghostwire hit
 * must not become an error toast because JB2A shipped a rename.
 */
function sequencerFile(files) {
  const db = globalThis.Sequencer?.Database;
  if (!db?.entryExists) return null;
  for (const file of files ?? []) {
    try {
      if (db.entryExists(file)) return file;
    } catch {
      /* keep trying the next one */
    }
  }
  return null;
}

/* -------------------------------------------- the built-in path */

/**
 * The fallback that needs nothing: two beats on `canvas.controls`.
 *
 * `canvas.controls` is where Foundry keeps its own transient canvas furniture (cursors, rulers,
 * pings), so effects drawn there sit above the tokens at `zIndex: 1000`, never persist, and are
 * never a document anybody has to clean up. Travel runs for `travelMs`, impact for
 * {@link IMPACT_MS}, and then the whole thing destroys itself — **one container and one ticker
 * callback for both beats**, because two of each is two things that can leak.
 *
 * 0.3.131 raised the impact hold from 420 ms. 420 was long enough to be technically correct and
 * short enough that a Director looking at the chat log missed it.
 */
const IMPACT_MS = 560;

/**
 * 0.3.130 (F) / 0.3.131 (D) — live ticker callbacks. A Set so `canvasTearDown`, `canvasReady` and
 * `deleteCombat` can force-remove every in-flight effect in one pass, preventing a leaked ticker
 * from painting against a dead canvas after a scene change, hot-reload, or module disable.
 *
 * Each entry holds the **container**, not a bare Graphics: 0.3.131's sprite rig puts a dozen
 * children under one display object, and they all have to go together.
 */
const liveFrames = new Set();

function teardownAllFrames() {
  for (const entry of liveFrames) {
    try { canvas?.app?.ticker?.remove(entry.frame); } catch { /* already gone */ }
    destroyDisplay(entry.display);
  }
  liveFrames.clear();
}

const lerp = (from, to, t) => ({ x: from.x + ((to.x - from.x) * t), y: from.y + ((to.y - from.y) * t) });
/** A bullet does not travel linearly on screen; it arrives. */
const easeOut = t => 1 - Math.pow(1 - t, 2.2);
const clamp01 = v => Math.max(0, Math.min(1, v));
const heading = (from, to) => Math.atan2(to.y - from.y, to.x - from.x);

/* ---------------------------- the sprite rig (primary) */

/**
 * Build every sprite one effect will ever need, up front.
 *
 * Built once and then only transformed, rather than created and destroyed per frame: allocating
 * inside a ticker is how a canvas effect turns into a stutter. Impact sprites start hidden and the
 * travel sprites are hidden when the impact takes over.
 *
 * @returns {object|null} null when the textures are not cached yet — the caller draws vectors.
 */
function createRig(container, { travel, style, color, core, sparks }) {
  if (!fxTexturesReady()) return null;
  const rig = { travel: null, impact: null, sparks: [] };

  if ((travel === "tracer") || (travel === "bolt")) {
    rig.travel = {
      beam: addFxSprite(container, "beam", { tint: color }),
      head: addFxSprite(container, "glow", { tint: core }),
      muzzle: addFxSprite(container, "flare", { tint: core }),
    };
  } else if (travel === "lunge") {
    rig.travel = { swing: addFxSprite(container, "slash", { tint: color }) };
  }

  rig.impact = {
    ring: (style === "muzzle") ? null : addFxSprite(container, "ring", { tint: color }),
    flash: addFxSprite(container, (style === "slash") ? "slash" : "flare", { tint: core }),
    glow: addFxSprite(container, "glow", { tint: color }),
  };
  for (let i = 0; i < (sparks ?? 0); i += 1) {
    rig.sparks.push(addFxSprite(container, "spark", { tint: core }));
  }

  const every = [
    ...Object.values(rig.travel ?? {}),
    ...Object.values(rig.impact).filter(Boolean),
    ...rig.sparks,
  ];
  if (every.some(sprite => !sprite)) return null;  // a texture went missing mid-flight
  for (const sprite of every) sprite.visible = false;
  return rig;
}

const showOnly = (rig, phase) => {
  for (const sprite of Object.values(rig.travel ?? {})) sprite.visible = (phase === "travel");
  for (const sprite of Object.values(rig.impact).filter(Boolean)) sprite.visible = (phase === "impact");
  for (const sprite of rig.sparks) sprite.visible = (phase === "impact");
};

/** The origin→target beat, in sprites. Mirrors {@link drawTravel}. */
function spriteTravel(rig, { travel, from, to, t, size, beamWidth }) {
  const ride = easeOut(t);
  if (!rig.travel) return;

  if (travel === "lunge") {
    // The crescent opens back toward the attacker, so the blade reads as sweeping across the
    // target's near side rather than orbiting it.
    const swing = rig.travel.swing;
    placeAt(swing, to, size * (1.15 + (0.75 * t)));
    swing.rotation = heading(to, from);
    swing.alpha = clamp01(1.4 - t);
    return;
  }

  const head = lerp(from, to, ride);
  // A tracer is a short bright segment chasing the head; a bolt is the whole beam growing out of
  // the caster. Same two sprites, one number apart.
  const trail = (travel === "tracer") ? Math.max(0, ride - 0.38) : 0;
  const tail = lerp(from, to, trail);
  const grow = (travel === "bolt") ? (0.75 + (0.45 * t)) : 1;
  layAlong(rig.travel.beam, tail, head, size * beamWidth * grow);
  rig.travel.beam.alpha = 0.95;
  placeAt(rig.travel.head, head, size * (0.55 + (0.25 * t)));
  rig.travel.head.alpha = 1;
  placeAt(rig.travel.muzzle, from, size * (1.0 + (0.6 * t)));
  rig.travel.muzzle.alpha = clamp01(1 - (t * 2.4));
}

/** The impact beat, in sprites. Mirrors {@link drawImpact}. */
function spriteImpact(rig, { style, color, from, to, t, size, impactSize, sparks }) {
  const span = size * impactSize;
  const fade = 1 - t;

  if (rig.impact.ring) {
    placeAt(rig.impact.ring, to, span * (0.28 + (1.05 * easeOut(t))));
    rig.impact.ring.alpha = fade * 0.95;
  }
  placeAt(rig.impact.flash, to, span * (0.95 - (0.25 * t)));
  rig.impact.flash.alpha = Math.pow(fade, 1.6);
  if (style === "slash") rig.impact.flash.rotation = from ? heading(to, from) : 0;
  else rig.impact.flash.rotation = t * 0.6;
  placeAt(rig.impact.glow, to, span * (0.45 + (0.55 * t)));
  rig.impact.glow.alpha = fade * 0.7;

  if (!sparks) return;
  const bias = from ? heading(from, to) : 0;
  const inner = span * (0.16 + (0.34 * easeOut(t)));
  const outer = inner + (span * (0.12 + (0.52 * easeOut(t))));
  for (let i = 0; i < rig.sparks.length; i += 1) {
    const angle = bias + ((Math.PI * 2 * i) / rig.sparks.length) + (t * 0.35);
    const dx = Math.cos(angle);
    const dy = Math.sin(angle);
    layAlong(
      rig.sparks[i],
      { x: to.x + (dx * inner), y: to.y + (dy * inner) },
      { x: to.x + (dx * outer), y: to.y + (dy * outer) },
      Math.max(2, size * 0.10 * fade),
    );
    rig.sparks[i].alpha = Math.pow(fade, 1.3);
  }
}

/* ---------------------------- the vector floor (no textures needed) */

/**
 * The origin→target beat in vectors: what leaves the shooter when the textures are not in hand yet.
 *
 * Every call goes through scripts/fx-canvas.mjs rather than PIXI directly, so the same source runs
 * on the PIXI 7 Foundry 14 ships and on the PIXI 8 that replaces it.
 */
function drawTravel(graphics, { travel, color, from, to, t, size }) {
  if (travel === "tracer") {
    const head = lerp(from, to, easeOut(t));
    const tail = lerp(from, to, Math.max(0, easeOut(t) - 0.38));
    strokePath(graphics, [tail, head], { color, alpha: 0.95, width: 4 });
    fillCircle(graphics, { x: from.x, y: from.y, radius: size * 0.35, color, alpha: 0.5 * (1 - t) });
    return;
  }
  if (travel === "bolt") {
    // A beam that grows out of the caster, with a glowing head. Two passes so it reads as a core
    // inside a halo rather than one flat line.
    const head = lerp(from, to, t);
    strokePath(graphics, [from, head], { color, alpha: 0.25, width: 9 });
    strokePath(graphics, [from, head], { color, alpha: 0.9, width: 4 });
    fillCircle(graphics, { x: head.x, y: head.y, radius: size * (0.18 + (0.12 * t)), color, alpha: 0.55 });
    return;
  }
  if (travel === "lunge") {
    // The swing arc Automated Animations draws, drawn here: a blade sweeping across the target's
    // near side, opening as the strike commits.
    const angle = heading(from, to);
    const reach = size * (0.9 + (0.5 * t));
    const sweep = (Math.PI * 0.55) * t;
    strokeArc(graphics, {
      x: to.x, y: to.y, radius: reach,
      start: angle + Math.PI - sweep, end: angle + Math.PI + sweep,
      color, alpha: 0.85, width: (5 * (1 - (0.4 * t))) + 2,
    });
  }
}

/** The impact beat in vectors: what happens where it lands. */
function drawImpact(graphics, { style, color, from, to, t, size }) {
  if (style === "spark") {
    // Radiating shards plus a tightening ring — a bullet strike, not an explosion.
    const ring = size * (0.22 + (0.42 * t));
    strokeCircle(graphics, { x: to.x, y: to.y, radius: ring, color, alpha: 0.85, width: 3 });
    const spread = size * (0.35 + (0.65 * t));
    const bias = from ? heading(from, to) : 0;
    for (let i = 0; i < 6; i += 1) {
      const angle = bias + ((Math.PI * 2 * i) / 6) + (t * 0.4);
      strokePath(graphics, [
        { x: to.x + (Math.cos(angle) * ring), y: to.y + (Math.sin(angle) * ring) },
        { x: to.x + (Math.cos(angle) * spread), y: to.y + (Math.sin(angle) * spread) },
      ], { color, alpha: 0.9, width: (3 * (1 - t)) + 2 });
    }
    return;
  }
  if (style === "slash") {
    const span = size * (0.8 + (0.4 * t));
    strokeQuad(graphics, {
      from: { x: to.x - span, y: to.y - (span * 0.6) },
      control: to,
      to: { x: to.x + span, y: to.y + (span * 0.6) },
      color, alpha: 0.9, width: (6 * (1 - t)) + 3,
    });
    return;
  }
  const radius = size * (0.5 + (2.2 * t));
  strokeCircle(graphics, {
    x: to.x, y: to.y, radius, color, alpha: 0.95,
    width: (5 * (1 - t)) + 2, fillAlpha: 0.28 * (1 - t),
  });
}

/* ---------------------------- the runner */

/**
 * Run both beats for one target.
 *
 * @returns {PIXI.Container|null} The container holding the effect, or null when there is no canvas.
 */
function drawHitFx({
  travel = null, travelMs = 0, style = "burst", color = 0xffffff, core = null,
  beamWidth = 0.18, impactSize = 1.8, sparks = 0,
  from = null, to = null, impact = true,
}) {
  const layer = canvas?.controls;
  if (!layer || !to || !globalThis.PIXI) return null;
  // 0.3.131 (A2): the whole grid square, not half of it. Every size below is a multiple of this.
  const size = canvas?.dimensions?.size ?? 100;
  const origin = (travel && from) ? from : null;
  const flight = origin ? Math.max(0, Math.floor(Number(travelMs) || 0)) : 0;
  // `impact: false` is the half-and-half case: Sequencer had an impact file but no projectile, so
  // Ghostwire draws only the travel beat and gets out of the way rather than stacking a second flash
  // on top of JB2A's.
  const total = flight + (impact ? IMPACT_MS : 0);
  if (!total) return null;

  const container = layer.addChild(new PIXI.Container());
  container.eventMode = "none";
  const rig = createRig(container, { travel, style, color, core: core ?? color, sparks });
  const graphics = rig ? null : container.addChild(new PIXI.Graphics());
  if (graphics) graphics.eventMode = "none";
  trace(`draw ${travel ?? "-"}/${style} via ${rig ? "sprites" : "vectors"}`, { from: origin, to, total });

  const start = performance.now();
  const entry = { display: container, frame: null };

  const frame = () => {
    if (container.destroyed || !canvas?.app?.ticker) {
      liveFrames.delete(entry);
      try { canvas?.app?.ticker?.remove(frame); } catch { /* already gone */ }
      return;
    }
    const elapsed = performance.now() - start;
    const travelling = !!flight && (elapsed < flight);
    // "done" is the `impact: false` tail: a frame where neither beat runs. Without it the impact
    // sprites would flip visible with untouched transforms — a white blob at the scene origin.
    if (rig) showOnly(rig, travelling ? "travel" : (impact ? "impact" : "done"));
    else graphics.clear();

    if (travelling) {
      container.alpha = 1;
      const beat = { travel, color, core: core ?? color, from: origin, to, t: elapsed / flight, size, beamWidth };
      if (rig) spriteTravel(rig, beat);
      else drawTravel(graphics, beat);
    } else if (impact) {
      const t = clamp01((elapsed - flight) / IMPACT_MS);
      container.alpha = rig ? 1 : (1 - t);          // the sprite rig fades per-sprite instead
      const beat = { style, color, core: core ?? color, from: origin, to, t, size, impactSize, sparks };
      if (rig) spriteImpact(rig, beat);
      else drawImpact(graphics, beat);
    }

    if (elapsed >= total) {
      canvas.app?.ticker?.remove(frame);
      destroyDisplay(container);
      liveFrames.delete(entry);
    }
  };

  entry.frame = frame;
  liveFrames.add(entry);
  canvas.app?.ticker?.add(frame);
  return container;
}

/* -------------------------------------------- playback */

function playSound(src) {
  const level = volume();
  if (!src || !(level > 0)) return;
  try {
    foundry.audio.AudioHelper.play({ src, volume: level, loop: false, channel: "interface" }, true);
  } catch (error) {
    console.warn(`${MODULE_ID} | hit FX sound failed`, error);
  }
}

/**
 * Points come off tokens as live PIXI objects; the wire wants two numbers.
 *
 * The token's UUID rides along when there is one. Nothing local uses it — it is there so a client
 * receiving the relay can ask whether it is allowed to see that token before it paints a tracer
 * pointing at it. A Director rolling a hidden ambusher's attack should not have the relay announce
 * where the ambusher is standing.
 */
const plain = point => (point
  ? { x: Number(point.x), y: Number(point.y), uuid: point.uuid ?? null }
  : null);

/**
 * 0.3.131 (A3) — tell every other client on this scene to draw the same beat.
 *
 * The same native `game.socket` channel scripts/mark.mjs and scripts/chrome-damage.mjs use; no
 * socketlib. Foundry does not echo an emit back to its sender, so there is no self-filter here.
 * `beats` is `"both"` normally and `"travel"` in the Sequencer half-and-half case, where JB2A is
 * already broadcasting its own impact and a second one would be a double flash.
 */
function emitHitFx(payload) {
  if (!broadcasting()) return;
  try {
    game?.socket?.emit(SOCKET, {
      op: "hitFx.play",
      sceneId: canvas?.scene?.id ?? null,
      ...payload,
    });
  } catch (error) {
    console.warn(`${MODULE_ID} | could not relay hit FX to the table`, error);
  }
}

function onHitFxSocket(payload) {
  if (payload?.op !== "hitFx.play") return;
  if (!enabled() || !broadcasting()) return;
  // Somebody else's scene is somebody else's business.
  if (payload.sceneId && canvas?.scene?.id && (payload.sceneId !== canvas.scene.id)) return;
  const at = (payload.at ?? []).filter(visibleHere);
  const from = visibleHere(payload.from) ? (payload.from ?? null) : null;
  if (!at.length && !from) return;                 // nothing this client is allowed to look at
  playHitFx(payload.kind, {
    from,
    at,
    name: payload.name ?? "",
    element: payload.element ?? null,             // 0.3.134 (E): the table sees the same colour
    silent: true,                                  // AudioHelper already broadcast the impact
    relay: false,                                  // and this client must not relay it onward
    mode: "builtin",                               // Sequencer broadcasts its own video
    impact: payload.beats !== "travel",
  });
}

/**
 * Play one hit effect. Never throws, never awaits anything the caller has to care about.
 *
 * @param {"gun"|"spell"|"melee"|"grenade"} kind
 * @param {object} [opts]
 * @param {{x: number, y: number}|null} [opts.from]  The attacker's token centre (travel origin).
 * @param {Array<{x: number, y: number}>} [opts.at]  Where it lands. Empty falls back to a muzzle flash.
 * @param {string} [opts.name]  The ability's name, so a spell picks its flavour.
 * @param {string|null} [opts.element]  A damage type ("fire", "cold", …). Beats the name-based flavour.
 * @param {boolean} [opts.silent]  Draw only — the sound already reached this client.
 * @param {boolean} [opts.relay]   Broadcast the resolved points to the rest of the table.
 * @param {"auto"|"builtin"} [opts.mode]  `builtin` never touches Sequencer.
 * @param {boolean} [opts.impact]  False draws the travel beat only.
 * @returns {{kind: string, sound: string, flavour: string|null, via: "sequencer"|"builtin"|"origin"|"none"}|null}
 */
export function playHitFx(kind, {
  from = null, at = [], name = "", element = null,
  silent = false, relay = true, mode = "auto", impact = true,
} = {}) {
  const profile = hitFxProfile(kind, name, { element });
  if (!profile || !enabled()) return null;

  if (!silent) playSound(profile.sound);

  const origin = plain(from);
  const points = (at ?? []).map(plain).filter(point => point && Number.isFinite(point.x) && Number.isFinite(point.y));
  const result = { kind, sound: profile.sound, flavour: profile.flavour, via: "none" };

  const builtin = ({ to, impact: wantImpact = true, travel = profile.travel }) => drawHitFx({
    travel, travelMs: profile.travelMs,
    style: profile.style, color: profile.color, core: profile.core,
    beamWidth: profile.beamWidth, impactSize: profile.impactSize, sparks: profile.sparks,
    from: origin, to, impact: wantImpact,
  });

  // A1: nothing downrange. A shot still has a muzzle, so the shooter's own token flashes rather
  // than the whole beat silently doing nothing — which is exactly how 0.3.130 read as "blank".
  if (!points.length) {
    if (!origin) {
      trace(`${kind}: no target and no origin — sound only`);
      return result;
    }
    drawHitFx({
      travel: null, travelMs: 0, style: "muzzle",
      color: profile.color, core: profile.core,
      impactSize: Math.min(1.2, profile.impactSize), sparks: 0,
      from: null, to: origin, impact: true,
    });
    if (relay) emitHitFx({ kind, name, element, from: origin, at: [], beats: "both" });
    return { ...result, via: "origin" };
  }

  const Seq = (mode === "auto") ? sequencer() : null;
  const impactFile = Seq ? sequencerFile(profile.sequencerFiles) : null;
  const travelFile = (Seq && profile.travel && origin) ? sequencerFile(profile.travelFiles) : null;
  if (Seq && (impactFile || travelFile)) {
    try {
      const sequence = new Seq();
      for (const point of points) {
        // The travel beat is a stretched-to-fit effect from the shooter to this target; the impact
        // beat lands on it. Either half may be missing from the table's JB2A install, and the
        // built-in beat fills in for whichever one is.
        if (travelFile) sequence.effect().file(travelFile).atLocation(origin).stretchTo(point);
        if (impactFile) sequence.effect().file(impactFile).atLocation(point).scale(0.7);
      }
      sequence.play();
      if (!travelFile && profile.travel && origin) {
        for (const point of points) builtin({ to: point, impact: false });
        if (relay) emitHitFx({ kind, name, element, from: origin, at: points, beats: "travel" });
      }
      return { ...result, via: "sequencer" };
    } catch (error) {
      console.warn(`${MODULE_ID} | Sequencer hit FX failed; falling back to the built-in beats`, error);
    }
  }

  for (const point of points) builtin({ to: point, impact });
  if (relay) emitHitFx({ kind, name, element, from: origin, at: points, beats: impact ? "both" : "travel" });
  return { ...result, via: "builtin" };
}

/* -------------------------------------------- the attack fire point */

/**
 * The Ghostwire gear behind an ability, when there is any.
 *
 * B49 stamps `fromGearId` on every ability it spawns from a weapon treasure, which is the only
 * link that survives renames, so it is tried first. A class ability comes back null and is then
 * classified from its own keywords and `_dsid` instead (0.3.128 A).
 */
function gearBehind(ability) {
  const gearId = ability?.getFlag?.(MODULE_ID, "fromGearId");
  if (!gearId) return null;
  return ability.actor?.items?.get?.(gearId) ?? null;
}

/** The kind of hit an ability result represents, or null. */
function kindForAbility(ability) {
  if (!ability) return null;
  const flags = gearFlags(gearBehind(ability));
  const system = ability.system ?? {};
  return classifyHit({
    thrownBlast: !!flags?.thrown,
    range: flags?.range ?? "",
    ammoFamily: flags?.ammoFamily ?? null,
    gunAbility: ammoCostForDsid(system._dsid) > 0,
    keywords: system.keywords ?? [],
    distanceType: system.distance?.type ?? "",
    dsid: system._dsid ?? "",
    damaging: hasDamageEffect(system),
  });
}

/** Every `abilityResult` part on a message, read through the ModelCollection trap B40 documents. */
function resultParts(message) {
  const parts = message?.system?.parts;
  if (!parts) return [];
  const list = Array.isArray(parts) ? parts : (parts.contents ?? Object.values(parts));
  return list.filter(part => (part?.type ?? part?.constructor?.TYPE) === "abilityResult");
}

/**
 * The centre of a token, whichever shape the caller has it in.
 *
 * A TokenDocument whose placeable is not on this client's canvas still has `x`/`y`/`width`/`height`
 * in grid units, which is enough — the relay may be describing a token the receiver cannot see.
 */
function tokenPoint(token) {
  if (!token) return null;
  const doc = token.document ?? token;
  const uuid = doc?.uuid ?? null;
  const centre = token.object?.center ?? token.center ?? null;
  if (centre && Number.isFinite(centre.x) && Number.isFinite(centre.y)) return { x: centre.x, y: centre.y, uuid };
  const grid = canvas?.dimensions?.size ?? 100;
  if (Number.isFinite(doc?.x) && Number.isFinite(doc?.y)) {
    return { x: doc.x + (((doc.width ?? 1) * grid) / 2), y: doc.y + (((doc.height ?? 1) * grid) / 2), uuid };
  }
  return null;
}

/**
 * May this client paint at this point?
 *
 * Only asked of a relayed beat. A point with no token behind it (a grenade's landing square) is
 * always fair game; a point that names a token this client cannot currently see is dropped, so the
 * relay never becomes a way to find a hidden enemy by watching where the tracers go.
 */
function visibleHere(point) {
  if (!point?.uuid) return true;
  try {
    const token = fromUuidSync(point.uuid)?.object ?? null;
    return !token || (token.visible !== false);
  } catch {
    return true;
  }
}

const uuidToPoint = uuid => {
  try {
    return tokenPoint(fromUuidSync(uuid));
  } catch {
    return null;
  }
};

/**
 * Token centres this attack was aimed at.
 *
 * **A1, the 0.3.131 root cause.** `message.system.targetTokens` was the only real source and it is
 * `undefined` on an ability card: Draw Steel puts `targets` on `BaseMessageModel`, the base for the
 * message subtypes *without* parts, and an ability use is a `StandardModel` whose schema is `parts`
 * alone. So the old code fell straight to the roller's live targets and produced nothing the moment
 * that set was empty. Five sources now, first non-empty wins; when all five come back empty,
 * {@link playHitFx} flashes the shooter's muzzle rather than drawing nothing:
 *
 *  1. `system.targetTokens` — free if a future system version grows it, and right for the message
 *     subtypes that already have it.
 *  2. `system.targets` — the same data one layer down, as UUIDs.
 *  3. the part's own targets, for a system version that moves them onto the roll.
 *  4. the **rolling user's** target set, read off the User document rather than off this client, so
 *     an observer resolves the same points the shooter did.
 *  5. this client's own targets.
 */
function targetPoints(message, userId = null) {
  const system = message?.system ?? {};
  const sources = [
    () => [...(system.targetTokens ?? [])].map(tokenPoint),
    () => [...(system.targets ?? [])].map(uuidToPoint),
    () => resultParts(message).flatMap(part => [
      ...[...(part?.targetTokens ?? [])].map(tokenPoint),
      ...[...(part?.targets ?? [])].map(target => (typeof target === "string" ? uuidToPoint(target) : tokenPoint(target))),
    ]),
    () => [...(game.users?.get?.(userId)?.targets ?? [])].map(tokenPoint),
    () => [...(game.user?.targets ?? [])].map(tokenPoint),
  ];
  for (const source of sources) {
    let points = [];
    try {
      points = source().filter(Boolean);
    } catch {
      points = [];                                 // a shape this system version does not have
    }
    if (points.length) return points;
  }
  return [];
}

/**
 * The attacker's token centre — where travel starts.
 *
 * The speaker's token id is the usual answer. When the card was spoken by an actor with no token id
 * on it (a synthetic speaker, a Director rolling from the sidebar), the actor's own token on this
 * scene is the next best thing, and the ability's owner is the last.
 */
function speakerPoint(message, ability = null) {
  const speaker = message?.speaker ?? {};
  const byToken = speaker.token ? canvas?.tokens?.get?.(speaker.token) : null;
  const direct = tokenPoint(byToken);
  if (direct) return direct;

  const actor = (speaker.actor ? game.actors?.get?.(speaker.actor) : null) ?? ability?.actor ?? null;
  if (!actor) return null;
  const tokens = actor.getActiveTokens?.(false, false) ?? [];
  for (const token of tokens) {
    const point = tokenPoint(token);
    if (point) return point;
  }
  return null;
}

/* -------------------------------------------- registration */

export function registerHitFx() {
  registerSettings();

  // 0.3.130 (F) / 0.3.131 (D) — harden canvas / ticker teardown. Force-remove every in-flight PIXI
  // effect on scene change, canvas teardown, or combat end so leaked tickers never paint against a
  // dead canvas, and re-warm the texture cache the teardown just emptied.
  Hooks.on("canvasTearDown", teardownAllFrames);
  Hooks.on("canvasReady", () => {
    teardownAllFrames();
    preloadFxTextures();
  });
  Hooks.on("deleteCombat", teardownAllFrames);
  Hooks.once("ready", () => {
    preloadFxTextures();
    game.socket.on(SOCKET, onHitFxSocket);
  });

  // One client fires it: the one whose action created the message, exactly as B40 does. 0.3.131
  // (A3) then relays the resolved points, so the rest of the table draws the same beat instead of
  // only hearing it.
  Hooks.on("createChatMessage", (message, options, userId) => {
    if (userId !== game.user.id) return;
    if (!enabled()) return;
    for (const part of resultParts(message)) {
      const ability = part.ability ?? (part.abilityUuid ? fromUuidSync(part.abilityUuid) : null);
      const kind = kindForAbility(ability);
      if (!kind) {
        trace(`no kind for ${ability?.name ?? "an unresolved ability"}`);
        continue;
      }
      const at = targetPoints(message, userId);
      const from = speakerPoint(message, ability);
      // 0.3.134 (E) — the element, when the card carries one. Hurl Element and its eight siblings are
      // typed to the hero's attunement before the roll, and a summon's strike is typed to the element
      // it was called with, so the damage type on the card is the truth about what colour this is.
      //
      // 0.3.135 (2) — and when the card says nothing, the **caster's attunement** does. A homebrew
      // Hurl Element, or one the attunement sync has not reached, is still the element the player
      // picked rather than arcane blue.
      const element = elementForFx(ability, attunementOf(ability?.actor ?? ability?.parent ?? null));
      trace(`${ability?.name ?? kind} -> ${kind}${element ? ` (${element})` : ""}`, { from, targets: at.length });
      playHitFx(kind, { from, at, name: ability?.name ?? "", element });
      return;                                      // one attack, one bang
    }
  });

  const module = game.modules.get(MODULE_ID);
  if (module) {
    module.api = {
      ...(module.api ?? {}),
      playHitFx,
      classifyHit,
      hasDamageEffect,
      spellFlavour,
      hitFxProfile,
      hitFxProfiles: () => HIT_FX_PROFILES,
      preloadFxTextures,
    };
  }

  console.log(`${MODULE_ID} | hit FX registered (${HIT_FX_KINDS.join(" / ")}; sprites from assets/fx, relayed to the table; Sequencer optional)`);
}
